#!/bin/sh
source /usr/local/bin/acq400_init_gpio_common.sh

echo 9 > /proc/sys/kernel/printk
echo file ad5696-i2c.c +p >/dev/ddc

if [ -e /mnt/local/ad5686.ko ]; then
    echo "LOAD PATCH MODULES"
    /sbin/insmod /mnt/local/ad5686.ko dyndbg=+p
    /sbin/insmod /mnt/local/ad5696-i2c.ko dyndbg=+p
else
    /sbin/insmod /usr/local/lib/modules/ad5686.ko     $SCDAC_DBG
    /sbin/insmod /usr/local/lib/modules/ad5696-i2c.ko $SCDAC_DBG
fi

/usr/local/CARE/load.overlay flashelf_overlay /mnt/flashelf_overlay.dtb

configure_1v_dac() {
    node=$(basename $2)
    site=${node#*@site}
    daclab=${node%@*}
    c1=${daclab#*dac}
	echo configure_dac $1 $node $site $c1
	for off in $(seq 0 3); do
	    c01=$(printf "%02d" $c1)
		ln -s $1/out_voltage${off}_raw /etc/acq400/$site/dac1vch$c01
		c1=$(($c1+1))
	done
}

configure_10v_dac() {
    node=$(basename $2)
    site=${node#*@site}
    daclab=${node%@*}
    c1=${daclab#*dac}
	echo configure_dac $1 $node $site $c1
	for off in $(seq 4 5); do
	    c01=$(printf "%02d" $c1)
		ln -s $1/out_voltage${off}_raw /etc/acq400/$site/dac10vch$c01
		c1=$(($c1+1))
	done
}

configure_1v_dac /sys/bus/iio/devices/iio:device1 dac1@site2
configure_10v_dac /sys/bus/iio/devices/iio:device1 dac1@site2

# gpios
configure_gpios() {
    site=$1
    echo configure_gpios $site
    for off in $(seq 1 8); do
        c01=$(printf "%01d" $off)
        ln -s /dev/acq.${site}.knobs/gpio_dir_$c01 /etc/acq400/$site/gpio_dir_$c01
        ln -s /dev/acq.${site}.knobs/gpio_out_$c01 /etc/acq400/$site/gpio_out_$c01
        ln -s /dev/acq.${site}.knobs/gpio_in_$c01 /etc/acq400/$site/gpio_in_$c01
    done
}

configure_gpios 2
